# Generated by Django 2.1.4 on 2018-12-13 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fenlei',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='分类')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
            },
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='主页标题')),
                ('content', models.CharField(max_length=60, verbose_name='主页内容')),
            ],
            options={
                'verbose_name': '主页',
                'verbose_name_plural': '主页',
            },
        ),
        migrations.CreateModel(
            name='WenZhang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='标题')),
                ('content', models.CharField(max_length=500, verbose_name='内容')),
                ('createTime', models.DateField(auto_now_add=True, verbose_name='时间')),
                ('zzname', models.CharField(max_length=12, verbose_name='作者')),
                ('fileLink', models.CharField(max_length=300, verbose_name='链接')),
                ('fenlei', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mydownload.Fenlei', verbose_name='分类')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
            },
        ),
    ]
