# Generated by Django 2.1.4 on 2018-12-13 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydownload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='content',
            field=models.TextField(verbose_name='主页内容'),
        ),
        migrations.AlterField(
            model_name='wenzhang',
            name='content',
            field=models.TextField(verbose_name='内容'),
        ),
    ]
