# Generated by Django 2.1.4 on 2018-12-13 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mydownload', '0002_auto_20181213_1034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileName', models.CharField(max_length=80)),
                ('fileLink', models.FileField(upload_to='./upload')),
            ],
            options={
                'verbose_name': '文件',
                'verbose_name_plural': '文件',
            },
        ),
        migrations.RemoveField(
            model_name='wenzhang',
            name='fileLink',
        ),
        migrations.AddField(
            model_name='files',
            name='wenZhang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mydownload.WenZhang', verbose_name='文章id'),
        ),
    ]
