# Generated by Django 2.1.4 on 2018-12-13 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mydownload', '0003_auto_20181213_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='wenZhang',
        ),
        migrations.AddField(
            model_name='wenzhang',
            name='fileLink',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='mydownload.Files', verbose_name='文件'),
        ),
    ]
