# Generated by Django 2.1.4 on 2018-12-13 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydownload', '0006_auto_20181213_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='fileLink',
            field=models.FileField(upload_to='upload'),
        ),
    ]
